# permissions for end users to edit grafanaenterpriselogstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: grafanaenterpriselogstoken-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gel
    app.kubernetes.io/part-of: gel
    app.kubernetes.io/managed-by: kustomize
  name: grafanaenterpriselogstoken-editor-role
rules:
- apiGroups:
  - loki.hamravesh.com
  resources:
  - grafanaenterpriselogstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.hamravesh.com
  resources:
  - grafanaenterpriselogstokens/status
  verbs:
  - get
