apiVersion: loki.gelops.com/v1alpha1
kind: GrafanaEnterpriseLogsToken
metadata:
  labels:
    app.kubernetes.io/name: grafanaenterpriselogstoken
    app.kubernetes.io/instance: grafanaenterpriselogstoken-sample
    app.kubernetes.io/part-of: gel
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gel
  name: lintechso-token
spec:
  accessPolicyRef: 
    name: "lintechso-access-policy"
  expirationTime: "2025-03-01T17:37:59.341728283Z"
