//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyRef) DeepCopyInto(out *AccessPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRef.
func (in *AccessPolicyRef) DeepCopy() *AccessPolicyRef {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsAccessPolicy) DeepCopyInto(out *GrafanaEnterpriseLogsAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Finalizers != nil {
		in, out := &in.Finalizers, &out.Finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsAccessPolicy.
func (in *GrafanaEnterpriseLogsAccessPolicy) DeepCopy() *GrafanaEnterpriseLogsAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsAccessPolicyList) DeepCopyInto(out *GrafanaEnterpriseLogsAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrafanaEnterpriseLogsAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsAccessPolicyList.
func (in *GrafanaEnterpriseLogsAccessPolicyList) DeepCopy() *GrafanaEnterpriseLogsAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsAccessPolicySpec) DeepCopyInto(out *GrafanaEnterpriseLogsAccessPolicySpec) {
	*out = *in
	in.TenantInfoRef.DeepCopyInto(&out.TenantInfoRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsAccessPolicySpec.
func (in *GrafanaEnterpriseLogsAccessPolicySpec) DeepCopy() *GrafanaEnterpriseLogsAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsAccessPolicyStatus) DeepCopyInto(out *GrafanaEnterpriseLogsAccessPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsAccessPolicyStatus.
func (in *GrafanaEnterpriseLogsAccessPolicyStatus) DeepCopy() *GrafanaEnterpriseLogsAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTenant) DeepCopyInto(out *GrafanaEnterpriseLogsTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Finalizers != nil {
		in, out := &in.Finalizers, &out.Finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTenant.
func (in *GrafanaEnterpriseLogsTenant) DeepCopy() *GrafanaEnterpriseLogsTenant {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTenantList) DeepCopyInto(out *GrafanaEnterpriseLogsTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrafanaEnterpriseLogsTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTenantList.
func (in *GrafanaEnterpriseLogsTenantList) DeepCopy() *GrafanaEnterpriseLogsTenantList {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTenantSpec) DeepCopyInto(out *GrafanaEnterpriseLogsTenantSpec) {
	*out = *in
	out.TenantInfo = in.TenantInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTenantSpec.
func (in *GrafanaEnterpriseLogsTenantSpec) DeepCopy() *GrafanaEnterpriseLogsTenantSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTenantStatus) DeepCopyInto(out *GrafanaEnterpriseLogsTenantStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTenantStatus.
func (in *GrafanaEnterpriseLogsTenantStatus) DeepCopy() *GrafanaEnterpriseLogsTenantStatus {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsToken) DeepCopyInto(out *GrafanaEnterpriseLogsToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Finalizers != nil {
		in, out := &in.Finalizers, &out.Finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsToken.
func (in *GrafanaEnterpriseLogsToken) DeepCopy() *GrafanaEnterpriseLogsToken {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTokenList) DeepCopyInto(out *GrafanaEnterpriseLogsTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrafanaEnterpriseLogsToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTokenList.
func (in *GrafanaEnterpriseLogsTokenList) DeepCopy() *GrafanaEnterpriseLogsTokenList {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrafanaEnterpriseLogsTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTokenSpec) DeepCopyInto(out *GrafanaEnterpriseLogsTokenSpec) {
	*out = *in
	out.AccessPolicyRef = in.AccessPolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTokenSpec.
func (in *GrafanaEnterpriseLogsTokenSpec) DeepCopy() *GrafanaEnterpriseLogsTokenSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaEnterpriseLogsTokenStatus) DeepCopyInto(out *GrafanaEnterpriseLogsTokenStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaEnterpriseLogsTokenStatus.
func (in *GrafanaEnterpriseLogsTokenStatus) DeepCopy() *GrafanaEnterpriseLogsTokenStatus {
	if in == nil {
		return nil
	}
	out := new(GrafanaEnterpriseLogsTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLabels) DeepCopyInto(out *MatchLabels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLabels.
func (in *MatchLabels) DeepCopy() *MatchLabels {
	if in == nil {
		return nil
	}
	out := new(MatchLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantInfo) DeepCopyInto(out *TenantInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantInfo.
func (in *TenantInfo) DeepCopy() *TenantInfo {
	if in == nil {
		return nil
	}
	out := new(TenantInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantInfoRef) DeepCopyInto(out *TenantInfoRef) {
	*out = *in
	if in.AccessPolicies != nil {
		in, out := &in.AccessPolicies, &out.AccessPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelectors != nil {
		in, out := &in.LabelSelectors, &out.LabelSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantInfoRef.
func (in *TenantInfoRef) DeepCopy() *TenantInfoRef {
	if in == nil {
		return nil
	}
	out := new(TenantInfoRef)
	in.DeepCopyInto(out)
	return out
}
